name: native_translator
description: "use native translate popup"
version: 0.0.6
homepage: https://github.com/fighttechvn/native_translator
issue_tracker: https://github.com/fighttechvn/native_translator/issues
screenshots:
  - description: "Easy to show dialog translate native iOS"
    path: docs/screenshot.png

environment:
  sdk: ^3.8.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fighttechvn.native_translator
        pluginClass: NativeTranslatorPlugin
      ios:
        pluginClass: NativeTranslatorPlugin
